using System.Text;
using Onboarding.Core.Configuration;
using Onboarding.Core.Naming;

namespace Onboarding.Core.LogonScripts;

/// <summary>Values for logon script placeholders (<c>{sam}</c>, <c>{homeUnc}</c>, <c>{department}</c>).</summary>
public sealed record LogonScriptValues(string SamAccountName, string HomeUnc, string Department);

/// <summary>
/// Generates the <c>.bat</c> logon script (SPEC §4.4, DECISIONS L1/L2). Returns bytes so the UI
/// preview and the written file are byte-identical (AK 3): strict ASCII, CRLF line endings,
/// trailing CRLF.
/// </summary>
public static class LogonScriptGenerator
{
    private const string NewLine = "\r\n";

    public static byte[] Generate(LogonScriptTemplate template, LogonScriptValues values)
    {
        ArgumentNullException.ThrowIfNull(template);
        ArgumentNullException.ThrowIfNull(values);

        var placeholders = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [Placeholders.Sam] = values.SamAccountName,
            [Placeholders.HomeUnc] = values.HomeUnc,
            [Placeholders.Department] = values.Department,
        };

        var lines = new List<string>();
        foreach (var letter in template.DisconnectDrives)
        {
            lines.Add($"net use {DriveLetter(letter)}: /del /y");
        }

        foreach (var mapping in template.ConnectDrives)
        {
            var unc = PlaceholderRenderer.Render(mapping.Unc, placeholders).Trim();
            if (unc.Length == 0)
            {
                throw new LogonScriptException($"Laufwerk {mapping.Letter}: UNC-Pfad fehlt.");
            }

            lines.Add($"net use {DriveLetter(mapping.Letter)}: {unc}");
        }

        foreach (var extra in template.ExtraLines)
        {
            lines.Add(PlaceholderRenderer.Render(extra, placeholders));
        }

        var sb = new StringBuilder();
        for (var i = 0; i < lines.Count; i++)
        {
            var line = lines[i];
            for (var c = 0; c < line.Length; c++)
            {
                var ch = line[c];
                if (ch > 0x7F)
                {
                    throw new LogonScriptException(
                        $"Zeile {i + 1} enthält das Nicht-ASCII-Zeichen '{ch}' (U+{(int)ch:X4}); cmd.exe liest .bat in der OEM-Codepage.");
                }

                if (ch is '\r' or '\n' || char.IsControl(ch) && ch != '\t')
                {
                    throw new LogonScriptException($"Zeile {i + 1} enthält ein Steuerzeichen (U+{(int)ch:X4}).");
                }
            }

            sb.Append(line).Append(NewLine);
        }

        return Encoding.ASCII.GetBytes(sb.ToString());
    }

    /// <summary>Text form of generated bytes for display (lossless, the bytes are ASCII).</summary>
    public static string ToText(byte[] content) => Encoding.ASCII.GetString(content);

    private static char DriveLetter(string letter)
    {
        var trimmed = letter.Trim().TrimEnd(':');
        if (trimmed.Length != 1 || !char.IsAsciiLetter(trimmed[0]))
        {
            throw new LogonScriptException($"Ungültiger Laufwerksbuchstabe '{letter}'.");
        }

        return char.ToLowerInvariant(trimmed[0]);
    }
}

public sealed class LogonScriptException : Exception
{
    public LogonScriptException()
    {
    }

    public LogonScriptException(string message)
        : base(message)
    {
    }

    public LogonScriptException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}
