// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onboarding.Data;

#nullable disable

namespace Onboarding.Data.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    [Migration("20261005135739_Phase4bHomeAclLogonServer")]
    partial class Phase4bHomeAclLogonServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Onboarding.Core.Configuration.AreaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OuCanonical")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OuDistinguishedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a4c0f6e-6f0b-4a51-9d0e-1a7a3f0c0001"),
                            Active = true,
                            Company = "CleanControlling GmbH",
                            Name = "TecSa",
                            OuCanonical = "CC.local/CleanControlling/Technical/Users",
                            OuDistinguishedName = "OU=Users,OU=Technical,OU=CleanControlling,DC=CC,DC=local",
                            SortOrder = 1,
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("6a4c0f6e-6f0b-4a51-9d0e-1a7a3f0c0002"),
                            Active = true,
                            Company = "CleanControlling Medical GmbH & Co. KG",
                            Name = "Bio",
                            OuCanonical = "CC.local/CleanControlling/Medical/Biology/Users",
                            OuDistinguishedName = "OU=Users,OU=Biology,OU=Medical,OU=CleanControlling,DC=CC,DC=local",
                            SortOrder = 2,
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("6a4c0f6e-6f0b-4a51-9d0e-1a7a3f0c0003"),
                            Active = true,
                            Company = "CleanControlling Medical GmbH & Co. KG",
                            Name = "Chemie",
                            OuCanonical = "CC.local/CleanControlling/Medical/Chemical/Users",
                            OuDistinguishedName = "OU=Users,OU=Chemical,OU=Medical,OU=CleanControlling,DC=CC,DC=local",
                            SortOrder = 3,
                            Version = 0L
                        });
                });

            modelBuilder.Entity("Onboarding.Core.Configuration.DepartmentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdGroups")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAdditionalAces")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Licenses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogonScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedMailboxes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Teams")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Onboarding.Core.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Onboarding.Core.Domain.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("ChecklistItems", (string)null);
                });

            modelBuilder.Entity("Onboarding.Core.Domain.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScopeRefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d1e2b3c-4f5a-4b6c-8d7e-000000000101"),
                            Active = true,
                            Description = "",
                            Mandatory = true,
                            Responsible = "IT",
                            Scope = "Global",
                            SortOrder = 10,
                            Title = "SwissSign-Zertifikat (S/MIME) erstellen",
                            Type = "Onboarding",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("8d1e2b3c-4f5a-4b6c-8d7e-000000000102"),
                            Active = true,
                            Description = "",
                            Mandatory = true,
                            Responsible = "IT",
                            Scope = "Global",
                            SortOrder = 20,
                            Title = "ILIAS-Konto anlegen",
                            Type = "Onboarding",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("8d1e2b3c-4f5a-4b6c-8d7e-000000000103"),
                            Active = true,
                            Description = "",
                            Mandatory = true,
                            Responsible = "IT",
                            Scope = "Global",
                            SortOrder = 30,
                            Title = "Mail an HR",
                            Type = "Onboarding",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("8d1e2b3c-4f5a-4b6c-8d7e-000000000104"),
                            Active = true,
                            Description = "",
                            Mandatory = true,
                            Responsible = "IT",
                            Scope = "Global",
                            SortOrder = 40,
                            Title = "Einladung EDV-Einführung",
                            Type = "Onboarding",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("8d1e2b3c-4f5a-4b6c-8d7e-000000000105"),
                            Active = true,
                            Description = "",
                            Mandatory = true,
                            Responsible = "IT",
                            Scope = "Global",
                            SortOrder = 50,
                            Title = "MFA einrichten (1Password)",
                            Type = "Onboarding",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("8d1e2b3c-4f5a-4b6c-8d7e-000000000106"),
                            Active = true,
                            Description = "",
                            Mandatory = true,
                            Responsible = "IT",
                            Scope = "Global",
                            SortOrder = 60,
                            Title = "In Multifunktionsdrucker eintragen",
                            Type = "Onboarding",
                            Version = 0L
                        },
                        new
                        {
                            Id = new Guid("8d1e2b3c-4f5a-4b6c-8d7e-000000000107"),
                            Active = true,
                            Description = "",
                            Mandatory = true,
                            Responsible = "IT",
                            Scope = "Global",
                            SortOrder = 70,
                            Title = "Rechnerarbeitsplatz einrichten",
                            Type = "Onboarding",
                            Version = 0L
                        });
                });

            modelBuilder.Entity("Onboarding.Core.Domain.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ApprovedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Derived")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DirectoryObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryObjectSid")
                        .HasMaxLength(184)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedInitialPassword")
                        .HasColumnType("BLOB");

                    b.Property<string>("IdentityOverride")
                        .HasColumnType("TEXT");

                    b.Property<string>("NeedsInputReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelfApprovalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SelfApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Input", "Onboarding.Core.Domain.Request.Input#PersonInput", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("AreaId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DepartmentId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("EffectiveDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Extension")
                                .HasMaxLength(4)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasDoctorTitle")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Mail")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ManagerObjectGuid")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("Onboarding.Core.Domain.RequestStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FirstAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForceRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WaitingSince")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "StepKey")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("RequestSteps", (string)null);
                });

            modelBuilder.Entity("Onboarding.Core.Operations.CertificateStatus", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Found")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NotAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("CertificateStatus", (string)null);
                });

            modelBuilder.Entity("Onboarding.Data.Entities.ConfigHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("ChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ConfigHistory", (string)null);
                });

            modelBuilder.Entity("Onboarding.Data.Entities.GlobalConfigRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalConfig", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Settings = "{\"DomainFqdn\":\"CC.local\",\"DomainNetBios\":\"\",\"UpnSuffix\":\"cleancontrolling.de\",\"MailPattern\":\"{firstInitial}.{lastName}@cleancontrolling.de\",\"ProxyAddressTemplates\":[\"SMTP:{mailLocal}@cleancontrolling.de\",\"smtp:{mailLocal}@cleancontrolling.com\"],\"DoctorTitle\":{\"Attribute\":\"extensionAttribute1\",\"Value\":\"Dr.\"},\"PhonePrefixE164\":\"\\u002B497465929678\",\"PhoneDisplayFormat\":\"\\u002B49 7465 929678-{DW}\",\"Home\":{\"Server\":\"DC01\",\"LocalRoot\":\"F:\\\\Home\",\"ShareNamePattern\":\"{sam}$\",\"UncPattern\":\"\\\\\\\\dc01\\\\{sam}$\",\"UserRight\":\"Modify\",\"AdditionalAces\":[{\"Principal\":\"SYSTEM\",\"Right\":\"FullControl\"},{\"Principal\":\"BUILTIN\\\\Administrators\",\"Right\":\"FullControl\"}]},\"LogonScript\":{\"Server\":\"DC03\",\"Path\":\"\\\\\\\\dc03\\\\NETLOGON\",\"FileNamePattern\":\"{sam}.bat\"},\"EntraConnectServer\":\"CC01\",\"UsageLocation\":\"DE\",\"LicenseMode\":\"Direct\",\"OneWinNativeOutlookEnabled\":false,\"Teams\":{\"VoiceRoutingPolicy\":\"INTStandard\",\"VoicemailPolicy\":\"CleanControlling Personal Voicemail\",\"VoicemailPromptLanguage\":\"de-DE\",\"PhoneNumberType\":\"DirectRouting\"},\"DisabledUsersOU\":\"\",\"TimeZone\":\"Europe/Berlin\",\"EnableLeadTime\":\"00:00:00\",\"RequestIdAttribute\":\"extensionAttribute15\",\"PasswordCertThumbprint\":\"\",\"Execution\":{\"PollInterval\":\"00:01:00\",\"BackoffSchedule\":[\"00:01:00\",\"00:02:00\",\"00:05:00\",\"00:10:00\",\"00:15:00\"],\"StepTimeout\":\"1.00:00:00\"},\"ApprovalPolicy\":\"SelfApprovalWithReason\"}",
                            Version = 0L
                        });
                });

            modelBuilder.Entity("Onboarding.Core.Domain.ChecklistItem", b =>
                {
                    b.HasOne("Onboarding.Core.Domain.Request", null)
                        .WithMany("Checklist")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Onboarding.Core.Domain.RequestStep", b =>
                {
                    b.HasOne("Onboarding.Core.Domain.Request", null)
                        .WithMany("Steps")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Onboarding.Core.Domain.Request", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
