<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Onboarding.Core\Onboarding.Core.csproj" />
    <ProjectReference Include="..\Onboarding.Data\Onboarding.Data.csproj" />
    <ProjectReference Include="..\Onboarding.Steps\Onboarding.Steps.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.Identity.Web.UI" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Onboarding.Tests" />
  </ItemGroup>
</Project>
